name: data_pipeline

profile: data_pipeline

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  data_pipeline:
    +schema: raw

vars:
  cast_top_n: 10
  crew_top_n: 10
  min_vote_count: 50
  min_films: 3

models:
  data_pipeline:
    +static_analysis: strict
    staging:
      +materialized: view
      +database: tesla_staging_db
      +schema: cinema
    intermediate:
      +materialized: table
      +database: tesla_staging_db
      +schema: cinema
    marts:
      +materialized: table
      +database: tesla_analytics_db
      +schema: cinema
      