name: data_pipeline

profile: data_pipeline

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  cast_top_n: 10
  crew_top_n: 10
  min_vote_count: 50
  min_films: 5
  top_n_movies: 10
  historic_start_date: "2026-01-01"

seeds:
  data_pipeline:
    +database: tesla_staging_db
    +schema: cinema
    snapshot_seed:
      +column_types:
        movie_id: int
        snapshot_date: date
        popularity: float
        vote_average: number(4,2)
        vote_count: int
        revenue: number

models:
  data_pipeline:
    +static_analysis: strict
    staging:
      +materialized: view
      +database: tesla_staging_db
      +schema: cinema
    intermediate:
      +materialized: table
      +database: tesla_staging_db
      +schema: cinema
    marts:
      dimension:
        +materialized: table
        +database: tesla_analytics_db
        +schema: cinema
      fact:
        +materialized: table
        +database: tesla_analytics_db
        +schema: cinema
      bridge:
        +materialized: view
        +database: tesla_analytics_db
        +schema: cinema
      analytics:
        +materialized: table
        +database: tesla_analytics_db
        +schema: cinema

      